### ISSUE TITLE
NullPointerException on placing QuantumTank

### ISSUE THREAD

**Issue by NosajDraw** [gigabit101/QuantumStorage#110]
Intermittent, but happens about 50% of the time.

Full crash log https://pastebin.com/AwbLJwK6

minecraft            | 1.12.2 
Forge                | 14.23.0.2500 
quantumstorage       | 4.4.1

java.lang.NullPointerException: Unexpected error
	at QuantumStorage.tiles.AdvancedTileEntity.readFromNBTWithoutCoords(AdvancedTileEntity.java:217)
	at QuantumStorage.tiles.TileQuantumTank.readFromNBTWithoutCoords(TileQuantumTank.java:123)
	at QuantumStorage.blocks.AdvancedBlock.func_180633_a(AdvancedBlock.java:132)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:186)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:476)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:193)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:228)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

**Comment by Realever** [comment]
i have the same crash after i place the quantum tank.but when i relog  a on the server the tank is placed and i have a second in my inventory

**Comment by boop5** [comment]
happens 100% of the time for me - but only if the tank contains something.
