### ISSUE TITLE
Quantum Bag Crash

### ISSUE THREAD

**Issue by Kirbyarm** [gigabit101/QuantumStorage#249]
Client crashed in single player, when pressing the hotkey assigned to open the Quantum Bag I had just crafted. Any idea what causes this and if there's a work around?

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Arrays$ArrayList.get(Unknown Source)
	at net.minecraft.util.NonNullList.get(SourceFile:44)
	at net.minecraft.entity.player.InventoryPlayer.func_70301_a(InventoryPlayer.java:708)
	at QuantumStorage.client.keybinding.KeyInputEventHandler.onKeyPressed(KeyInputEventHandler.java:40)
	at QuantumStorage.client.keybinding.KeyInputEventHandler.handleKeyInputEvent(KeyInputEventHandler.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3068_KeyInputEventHandler_handleKeyInputEvent_KeyInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:565)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2017)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Kirbyarm** [comment]
Some other information. The key bind was Ctrl + R. The bag opens fine if I right click from the hotbar, but it crashes when opening using the keybind. This has happened 3 times in a row without fail now.

**Comment by Kirbyarm** [comment]
More information, on reboot number 4. If the bag is moved off of the hotbar and the keybind is pressed, it does not crash, and opens normally. But if the item is in hand and you use the keybind it crashes. I will test if in-hand matters next.

**Comment by Kirbyarm** [comment]
Yeah, it only crashes when you press the keybind while the bag itself it in-hand. If it's anywhere else on the tool bar or inventory it doesn't crash on keypress.
